version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/known_hosts
      - run: "echo 'Host * \nStrictHostKeyChecking no\nUserKnownHostsFile /dev/null' >> ~/.ssh/config"
      - run: ssh root@mesg.com "cd ~/mesg.com; git pull; docker-compose -p mesg up --build -d"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
